# Generated by Django 2.0.2 on 2018-08-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='estados.Estado'),
        ),
    ]
