# Generated by Django 2.0.2 on 2018-08-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(default='', max_length=50)),
                ('texto', models.CharField(default='', max_length=5000)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
