# Generated by Django 2.0.2 on 2018-08-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocalizacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('geolocalizacao', models.ForeignKey(default=None, on_delete=None, related_name='campis', to='geolocalizacoes.Geolocalizacao')),
            ],
        ),
    ]
