# Generated by Django 2.0.2 on 2018-08-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0001_initial'),
        ('campis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campi',
            name='universidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campis', to='universidades.Universidade'),
        ),
        migrations.AlterUniqueTogether(
            name='campi',
            unique_together={('nome', 'universidade')},
        ),
    ]
