# Generated by Django 2.0.2 on 2018-08-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
        ('campis', '0002_auto_20180819_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='campi',
            name='cidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campis', to='cidades.Cidade'),
        ),
    ]
