# Generated by Django 2.0.2 on 2018-08-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cell_phone',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userType',
            new_name='tipoUsuario',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
