# Generated by Django 2.0.2 on 2018-08-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20180813_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='grupoPet',
            new_name='grupo_pet',
        ),
    ]
