# Generated by Django 2.0.2 on 2018-08-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180813_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grupo_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='grupospet.GrupoPet'),
        ),
    ]
