# Generated by Django 2.0.2 on 2018-08-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_lon', models.FloatField()),
                ('geo_lat', models.FloatField()),
            ],
        ),
    ]
