# Generated by Django 2.0.2 on 2018-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('area_do_conhecimento', models.CharField(blank=True, max_length=20, null=True)),
                ('interdisciplinar', models.BooleanField(default=True)),
            ],
        ),
    ]
