# Generated by Django 2.0.2 on 2018-08-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('grupospet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopet',
            name='projetos',
            field=models.ManyToManyField(to='projetos.Projeto'),
        ),
    ]
