# Generated by Django 2.1 on 2018-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupospet', '0002_grupopet_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupopet',
            name='projetos',
            field=models.ManyToManyField(null=True, to='projetos.Projeto'),
        ),
    ]
