# Generated by Django 2.0.2 on 2018-08-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacoes', '0001_initial'),
        ('grupospet', '0005_auto_20180816_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopet',
            name='geolocalizacao',
            field=models.ForeignKey(default=None, on_delete=None, to='geolocalizacoes.Geolocalizacao'),
        ),
    ]
