# Generated by Django 2.0.2 on 2018-08-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campis', '0001_initial'),
        ('grupospet', '0006_grupopet_geolocalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopet',
            name='campi',
            field=models.ForeignKey(default=None, on_delete=None, related_name='grupospet', to='campis.Campi'),
        ),
        migrations.AlterField(
            model_name='grupopet',
            name='geolocalizacao',
            field=models.ForeignKey(default=None, on_delete=None, related_name='grupospet', to='geolocalizacoes.Geolocalizacao'),
        ),
    ]
